package com.CommunicateObject;

public enum MODE {
    MSG_MODE,USER_MODE,ROOM_MODE,PICTURE_MODE,REPAINT_MODE,LOGIN_MODE,
    REGISTER_MODE,ROOM_MAKE_MODE,ENDING_START_MODE,ENDING_NEXT_MODE,
    ENDING_PREV_MODE, SUCCESSED,FAILED,ROOM_VIEW,GAME_START_MODE,
    ROOM_INFO,TEMP,REPAINT_NOTIFY,GAME_TWO_CHOICE,GAME_ONE_CHOICE,
    NEXT_ROUND,WAITING;
}
